######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 12 00:05:05 2014
######################################################################

TEMPLATE = app
TARGET = DAZL
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += pcbmill.ui
SOURCES += main.cpp
RESOURCES += pcbmill.qrc
QT += webkit